# Generated by Django 4.2.11 on 2024-03-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options'),
        ('shop', '0003_product_price_gte_product_stock_gte'),
    ]

    operations = [
    ]
