# Generated by Django 5.0.1 on 2024-02-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mailed',
            field=models.BooleanField(default=False),
        ),
    ]
